server:
  port: 8041

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: localhost:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
# springboot默认的日志级别是info ,feign的dubug日志级别就不会输出
logging:
  level:
    com.zhx.order.feign: debug
#feign 局部日志配置
#feign:
#  client:
#    config:
#      stock-service:
#        loggerLevel: BASIC
