server:
  port: 8041

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: localhost:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public

feign:
  sentinel:
    #开启openfeign对sentinel的整合
    enabled: true