server:
  port: 8070
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/seata_order?characterEncoding=utf8&userSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #初始化连接大小
      min-idle: 5  #最小连接池数量
      max-active: 20 #最大连接池数量
      max-wait: 60000  #获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL  #测试连接
      test-while-idle: true #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-on-borrow: false  #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false  #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      max-pool-prepared-statement-per-connection-size: 20  #开启poolPreparedStatements后生效
      filters: stat,wall   #配置扩展插件，常用的插件有=>stat:监控统计  wall:防御sql注入
      #通过connectProperties属性来打开mergeSql功能;慢SQL记录
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
  application:
    name: alibaba-seata-order
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
    alibaba:
      seata:
        tx-service-group: guangzhou  #事务分组
mybatis:
  mapper-locations: classpath:com/zhx/mapper/*.xml
  #type-aliases-package: com.zhx.pojo #开启别名
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
seata:
  #配置seata的注册中心，告诉seata client 怎么去访问seata server
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848 #seata server 所在的nacos服务地址
      application: seata-server # seata server 的服务名 seata-server
      username: nacos
      password: nacos
      group: SEATA_GROUP
  #配置seata的配置中心，可以读取seata client的一些配置
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848 #seata server 所在的nacos服务地址
      username: nacos
      password: nacos
      group: SEATA_GROUP

