server:
  port: 8040

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: localhost:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
    loadbalancer:
      ribbon:
        enabled: false
  main:
    allow-bean-definition-overriding: true