server:
  port: 8030

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: localhost:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
#被调用的服务名
stock-service:
  ribbon:
    #指定使用Nacos提供的负载均衡策略
    #NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    NFLoadBalancerRuleClassName: com.zhx.ribbon.customRule.CustomRule
ribbon:
  eager-load:
    #开启饥饿加载
    enabled: true
    #配置stock-service使用ribbon饥饿加载，多个使用逗号分隔
    clients: stock-service