server:
  port: 8020

spring:
  application:
    name: order-nacos
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: localhost:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
